# -*- coding: utf-8 -*-
"""criminal_preprocessed_data+fir_preprocessed_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-eV1BjQGXz0sjumHkGc_aMu0qFMIFYn
"""

import numpy as np
import pandas as pd

df1=pd.read_excel('/content/Accused_final_1.xlsx')

df1.head()

df1.shape

import pandas as pd
from sklearn.model_selection import train_test_split


# Define the number of rows you want to retain in the dataset
new_rows_count = 10000

# Define the stratification column
strat_col = 'Profession'

# Randomly split the data into strata
strata_df = pd.DataFrame()
for profession in df1[strat_col].unique():
    profession_df = df1[df1[strat_col] == profession]
    profession_df = profession_df.sample(n=int(new_rows_count * len(profession_df) / len(df1)), random_state=42)
    strata_df = pd.concat([strata_df, profession_df])

# Shuffle the strata to remove any potential order bias
strata_df = strata_df.sample(frac=1, random_state=42)

# Save the result as a new csv file
strata_df.to_csv("stratified_sample.csv", index=False)

DF1=pd.read_csv('/content/stratified_sample.csv')

DF1.head()

DF1.shape

df2=pd.read_excel('/content/cleaned_fir.xlsx')

df2.shape

df2.head()

new_rows_count = 20000

# Define the stratification column
strat_col = 'CrimeGroup_Name'

# Randomly split the data into strata
strata_df = pd.DataFrame()
for crime in df2[strat_col].unique():
    crime_df = df2[df2[strat_col] == crime]
    crime_df = crime_df.sample(n=int(new_rows_count * len(crime_df) / len(df1)), random_state=42)
    strata_df = pd.concat([strata_df, crime_df])

# Shuffle the strata to remove any potential order bias
strata_df = strata_df.sample(frac=1, random_state=42)

# Save the result as a new csv file
strata_df.to_csv("stratified2_sample.csv", index=False)

DF2=pd.read_csv('/content/stratified2_sample.csv')

DF2.head()

DF2.shape

merged_df = pd.merge(DF1, DF2, on='FIRNo', how='inner')

merged_df.head()

merged_df.shape

merged_df.isnull().sum()

merged_df.duplicated().sum()

merged_df.drop_duplicates(inplace=True)

merged_df.shape

merged_df.to_excel('CRIMINAL.xlsx', index=False)