# -*- coding: utf-8 -*-
"""fir_preprocessed_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FK1koTRGhrmAIFKW-0r_LCD-kDCnXI0
"""

import pandas as pd

df_fir=pd.read_csv('/content/FIR_Details_Data.csv')

df_fir.head()

df_fir.columns

df_fir.shape

columns_to_extract = ["FIRNo", "CrimeGroup_Name", "Latitude","Longitude"]

# Create a new DataFrame with only the desired columns
extracted_data = df_fir[columns_to_extract]

# Save the extracted data to a new CSV file
extracted_data.to_csv("extracted_dataset_fir.csv", index=False)

df_ex=pd.read_csv('/content/extracted_dataset_fir.csv')

df_ex.head()

df_ex.isnull().sum()

df_ex.dropna(subset=['CrimeGroup_Name','Latitude','Longitude'],inplace=True)

df_ex.shape

filename='cleaned_fir.xlsx'
df_ex.to_excel(filename, index=False)

df_x=pd.read_excel('/content/cleaned_fir.xlsx')

df_x.head()

