# Generated by Django 5.0.4 on 2024-04-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeDetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
