# Generated by Django 5.0.4 on 2024-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeDetection', '0002_crime_correlation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rowdy_sheeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('rowdy_no', models.IntegerField(null=True)),
            ],
        ),
    ]
