# Generated by Django 5.0.4 on 2024-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeDetection', '0003_rowdy_sheeters'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdy_sheeters',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
